=== BeatrizCamarzanaNistal/2324_lmsgi/ud4/04/04.dtd
<!ELEMENT curriculum (nombre+, fecha, residencia, datos)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT residencia (ciudad, pais)>
        <!ELEMENT ciudad (#PCDATA)>
        <!ELEMENT pais (#PCDATA)>
    <!ELEMENT datos (telefono?, correo?, linkedln?, descripcion*, habilidad*, estudios*, experiencia*)> 
    <!--       + -> 1 o mas, * -> 0 o mas, ? -> 0 o 1      -->
        <!ELEMENT telefono (#PCDATA)>
        <!ELEMENT correo (#PCDATA)>
        <!ELEMENT linkedln (#PCDATA)>
        <!ELEMENT descripcion (#PCDATA)>
        <!ELEMENT habilidad (#PCDATA)>
        <!ELEMENT estudios (#PCDATA)>
        <!ELEMENT experiencia (#PCDATA)>
        <!ATTLIST curriculum xmlns:xsi CDATA #IMPLIED >
        <!ATTLIST curriculum xsi:noNamespaceSchemaLocation CDATA #IMPLIED >

=== BeatrizCamarzanaNistal/2324_lmsgi/ud4/04/04.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curriculum SYSTEM "04.dtd">
<curriculum xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="04.xsd">
    <nombre>Beatriz Camarzana</nombre>
    <fecha>2005</fecha>
    <residencia>
        <ciudad>Zamora</ciudad>
        <pais>Spain</pais>
    </residencia>
    <datos>
        <telefono>638291920</telefono>
        <correo>beatriz@gmail.com</correo>
        <linkedln>beatriz_05</linkedln>
        <descripcion>Entusiasta y trabajadora. Con ganas de aprender</descripcion>
        <habilidad>Ingles: B1</habilidad>
        <estudios>ESO, BACH tecnologico</estudios>
        <experiencia>8 meses. Hosteleria</experiencia>
    </datos>
</curriculum>
