=== BeatrizCamarzanaNistal/2324_lmsgi/ud4/05/05.dtd
<!ELEMENT company (employee)>
    <!ELEMENT employee (FirstName*, LastName*, ContacNo*, Email*, Address*)>
    <!ELEMENT FirstName (#PCDATA)>
    <!ELEMENT LastName (#PCDATA)>
    <!ELEMENT ContacNo (#PCDATA)>
    <!ELEMENT Email (#PCDATA)>
    <!ELEMENT Address (City, State, Zip)>
        <!ELEMENT City (#PCDATA)>
        <!ELEMENT State (#PCDATA)>
        <!ELEMENT Zip (#PCDATA)>
        <!ATTLIST company xmlns:xsi CDATA #IMPLIED >
        <!ATTLIST company xsi:noNamespaceSchemaLocation CDATA #IMPLIED >

=== BeatrizCamarzanaNistal/2324_lmsgi/ud4/05/05.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE company SYSTEM "05.dtd" >
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="05.xsd">
    <employee>
        <FirstName>Juan</FirstName>
        <LastName>Sanchez</LastName>
        <ContacNo>123456789</ContacNo>
        <Email>juansanchez@company.com</Email>
        <Address>
            <City>Bangalore</City>
            <State>Karnataka</State>
            <Zip>560212</Zip>
        </Address>
    </employee>
</company>
